"""Create the LYFE ID sequence.

This runs before the autogenerated table baseline so that the sequence exists
independently of the models. LYFE IDs start at 1 -> "0001".

Revision ID: 0001_lyfe_id_sequence
Revises:
"""
from alembic import op

revision = "0001_lyfe_id_sequence"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS lyfe_id_seq START WITH 1 INCREMENT BY 1")


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS lyfe_id_seq")
